version: 1.0.{build}
skip_tags: true
shallow_clone: true
clone_depth: 1

# Only fill in ChocoMinorVersionNumber if there's a problem with the package.
environment:
  CHOCOLATEY_API_KEY:
    secure: nl5YRBS+wcVhpEJN3GqQxhqRyOMPgHXmRK6vhhk8oJD6fV3T+ecEpmjlYFthwXRz
  CHROMEDRIVER_VERSION_NUMBER: 81.0.4044.69
  ChocoMinorVersionNumber: 0

cache:
  - packages ->  **\packages.config

branches:
  only:
    - master

build_script:
  - ps: ./chromedriver/push-chocolatey.ps1 -apiKey $env:CHOCOLATEY_API_KEY -versionNumber $env:CHROMEDRIVER_VERSION_NUMBER -chocoMinorVersionNumber $env:ChocoMinorVersionNumber
